version: "3.7"
services:
  front:
    build:
      context: ./landbell-vuejs/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: vuejs-landbell
    volumes:
      - ./landbell-vuejs/:/usr/src/app
      - /usr/src/app/node_modules
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
  api:
    build:
      args:
        user: landbell
        uid: 1000
      context: ./landbell-laravel
      dockerfile: ./Dockerfile
    image: landbell-laravel
    container_name: laravel
    restart: always 
    working_dir: /var/www/
    volumes:
      - ./landbell-laravel:/var/www
      - ./landbell-laravel/.env.example:/var/www/.env
    depends_on:
      - mysql
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./landbell-laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
